// controllers/renewal.controller.js
const Renewal = require('../model/renewalmodal');
const nodemailer = require("nodemailer");
const cron = require("node-cron");

// ==================================================
// ===== Mail Transporter (Gmail + App Password) =====
// ==================================================
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "jcs@jecc.ac.in",
    pass: "lbak wqdd keih qagt",
  },
});

// ==================================================
// ===== Fixed Recipients =====
// ==================================================

 const FIXED_RECIPIENTS = [    "ansonneelamkavil@jecc.ac.in",   "debinolakkengil@jecc.ac.in",   "jcs@jecc.ac.in", ];
// ==================================================
// ===== Date Utility Functions =====
// ==================================================
function parseDate(dateString) {
  if (!dateString) return new Date();
  
  // If it's already a Date object
  if (dateString instanceof Date) return new Date(dateString);
  
  // If it's in DD/MM/YYYY format
  if (typeof dateString === 'string' && dateString.includes('/')) {
    const parts = dateString.split('/');
    if (parts.length === 3) {
      // DD/MM/YYYY format
      const day = parseInt(parts[0], 10);
      const month = parseInt(parts[1], 10) - 1; // Months are 0-indexed
      const year = parseInt(parts[2], 10);
      return new Date(year, month, day);
    }
  }
  
  // Default Date parsing for other formats
  return new Date(dateString);
}

function formatDateForDisplay(date) {
  return date.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric'
  });
}

// ==================================================
// ===== Professional HTML Template for Upcoming Renewals =====
// ==================================================
function buildUpcomingTemplate(name, type, renewalDate, project, daysLeft) {
  const displayDate = formatDateForDisplay(parseDate(renewalDate));
  
  return `
  <div style="font-family: Arial, sans-serif; background:#f4f6f8; padding:30px;">
    <div style="max-width:600px; margin:auto; background:#fff; border-radius:10px; padding:25px; box-shadow:0 4px 12px rgba(0,0,0,0.1);">
      
      <h2 style="color:#1a73e8; text-align:center; margin-bottom:20px;">
        🔔 Renewal Reminder
      </h2>

      <p style="font-size:16px; color:#333;">Dear Team,</p>
      <p style="font-size:16px; color:#333;">
        This is a reminder that the following renewal is approaching:
      </p>

      <table style="width:100%; border-collapse: collapse; margin:20px 0; font-size:15px;">
        <tr>
          <td style="padding:10px; border:1px solid #ddd; background:#f9f9f9;"><strong>Name</strong></td>
          <td style="padding:10px; border:1px solid #ddd;">${name}</td>
        </tr>
        <tr>
          <td style="padding:10px; border:1px solid #ddd; background:#f9f9f9;"><strong>Type</strong></td>
          <td style="padding:10px; border:1px solid #ddd;">${type}</td>
        </tr>
        <tr>
          <td style="padding:10px; border:1px solid #ddd; background:#f9f9f9;"><strong>Project</strong></td>
          <td style="padding:10px; border:1px solid #ddd;">${project || "—"}</td>
        </tr>
        <tr>
          <td style="padding:10px; border:1px solid #ddd; background:#f9f9f9;"><strong>Renewal Date</strong></td>
          <td style="padding:10px; border:1px solid #ddd; color:#d93025; font-weight:bold;">
            ${displayDate}
          </td>
        </tr>
        <tr>
          <td style="padding:10px; border:1px solid #ddd; background:#f9f9f9;"><strong>Days Left</strong></td>
          <td style="padding:10px; border:1px solid #ddd; color:#d93025; font-weight:bold;">
            ${daysLeft} days
          </td>
        </tr>
      </table>

      <p style="font-size:16px; color:#d93025; font-weight:bold; text-align:center;">
        ⚠️ Please ensure this renewal is completed before the due date.
      </p>

      <p style="margin-top:30px; font-size:15px; color:#555;">
        Regards,<br/>
        <strong>Renewal Tracker System</strong>
      </p>

      <hr style="margin:25px 0; border:0; border-top:1px solid #eee;"/>
      <small style="display:block; text-align:center; color:#777;">
        This is an automated email generated by Renewal Tracker.
      </small>
    </div>
  </div>
  `;
}

// ==================================================
// ===== Professional HTML Template for Expired Renewals =====
// ==================================================
function buildExpiredTemplate(name, type, renewalDate, project, daysOverdue) {
  const displayDate = formatDateForDisplay(parseDate(renewalDate));
  
  return `
  <div style="font-family: Arial, sans-serif; background:#f4f6f8; padding:30px;">
    <div style="max-width:600px; margin:auto; background:#fff; border-radius:10px; padding:25px; box-shadow:0 4px 12px rgba(0,0,0,0.1);">
      
      <h2 style="color:#e84118; text-align:center; margin-bottom:20px;">
        🚨 EXPIRED Renewal Alert
      </h2>

      <p style="font-size:16px; color:#333;">Dear Team,</p>
      <p style="font-size:16px; color:#333;">
        <strong style="color:#e84118;">URGENT:</strong> The following renewal has expired and requires immediate attention:
      </p>

      <table style="width:100%; border-collapse: collapse; margin:20px 0; font-size:15px;">
        <tr>
          <td style="padding:10px; border:1px solid #ddd; background:#f9f9f9;"><strong>Name</strong></td>
          <td style="padding:10px; border:1px solid #ddd;">${name}</td>
        </tr>
        <tr>
          <td style="padding:10px; border:1px solid #ddd; background:#f9f9f9;"><strong>Type</strong></td>
          <td style="padding:10px; border:1px solid #ddd;">${type}</td>
        </tr>
        <tr>
          <td style="padding:10px; border:1px solid #ddd; background:#f9f9f9;"><strong>Project</strong></td>
          <td style="padding:10px; border:1px solid #ddd;">${project || "—"}</td>
        </tr>
        <tr>
          <td style="padding:10px; border:1px solid #ddd; background:#f9f9f9;"><strong>Renewal Date</strong></td>
          <td style="padding:10px; border:1px solid #ddd; color:#e84118; font-weight:bold;">
            ${displayDate}
          </td>
        </tr>
        <tr>
          <td style="padding:10px; border:1px solid #ddd; background:#f9f9f9;"><strong>Status</strong></td>
          <td style="padding:10px; border:1px solid #ddd; color:#e84118; font-weight:bold;">
            EXPIRED (${daysOverdue} days overdue)
          </td>
        </tr>
      </table>

      <p style="font-size:16px; color:#e84118; font-weight:bold; text-align:center;">
        🚨 IMMEDIATE ACTION REQUIRED! Please renew this as soon as possible.
      </p>

      <p style="margin-top:30px; font-size:15px; color:#555;">
        Regards,<br/>
        <strong>Renewal Tracker System</strong>
      </p>

      <hr style="margin:25px 0; border:0; border-top:1px solid #eee;"/>
      <small style="display:block; text-align:center; color:#777;">
        This is an automated email generated by Renewal Tracker.
      </small>
    </div>
  </div>
  `;
}

// ==================================================
// ===== Mail Functions =====
// ==================================================
async function sendUpcomingMail(name, type, renewalDate, project, daysLeft) {
  try {
    const displayDate = formatDateForDisplay(parseDate(renewalDate));
    const subject = `Reminder: Renewal for ${name} (${type}) due in ${daysLeft} days (${displayDate})`;
    const html = buildUpcomingTemplate(name, type, renewalDate, project, daysLeft);

    await transporter.sendMail({
      from: `"Renewal Reminder" <jcs@jecc.ac.in>`,
      to: FIXED_RECIPIENTS,
      subject,
      html,
    });

    console.log(`✅ Upcoming mail sent for ${name} (${type}) - ${daysLeft} days left (Due: ${displayDate})`);
  } catch (err) {
    console.error("❌ Upcoming mail error:", err.message);
  }
}

async function sendExpiredMail(name, type, renewalDate, project, daysOverdue) {
  try {
    const displayDate = formatDateForDisplay(parseDate(renewalDate));
    const subject = `URGENT: Renewal for ${name} (${type}) EXPIRED ${daysOverdue} days ago (${displayDate})`;
    const html = buildExpiredTemplate(name, type, renewalDate, project, daysOverdue);

    await transporter.sendMail({
      from: `"Renewal Alert" <jcs@jecc.ac.in>`,
      to: FIXED_RECIPIENTS,
      subject,
      html,
    });

    console.log(`🚨 Expired mail sent for ${name} (${type}) - ${daysOverdue} days overdue (Was due: ${displayDate})`);
  } catch (err) {
    console.error("❌ Expired mail error:", err.message);
  }
}

// ==================================================
// ===== Core Reminder Logic (Reusable) =====
// ==================================================
// =================== CORE REMINDER LOGIC ===================
async function sendRemindersCore() {
  const today = new Date();
  today.setHours(0, 0, 0, 0); // normalize today to 00:00

  try {
    const allRenewals = await Renewal.find().lean();
    console.log(`📊 Total renewals in database: ${allRenewals.length}`);

    let upcomingCount = 0;
    let expiredCount = 0;

    for (const r of allRenewals) {
      // Skip if already renewed
      if (r.isRenewed) continue;

      const recordDate = parseDate(r.renewalDate);
      const diffDays = Math.ceil((recordDate - today) / (1000 * 60 * 60 * 24)); // days difference

      // =================== UPCOMING RENEWALS ===================
      // Send daily reminder if 0 < diffDays <= 15
      if (diffDays > 0 && diffDays <= 15) {
        await sendUpcomingMail(r.name, r.type, r.renewalDate, r.project, diffDays);
        upcomingCount++;
      }

      // =================== EXPIRED RENEWALS ===================
      // Send alert if renewal date has passed
      if (diffDays < 0) {
        await sendExpiredMail(r.name, r.type, r.renewalDate, r.project, Math.abs(diffDays));
        expiredCount++;
      }
    }

    console.log(`📧 ${upcomingCount} upcoming reminder mails and ${expiredCount} expired alert mails sent successfully`);

    return { upcoming: upcomingCount, expired: expiredCount };

  } catch (err) {
    console.error("❌ Reminder job error:", err.message);
    return { upcoming: 0, expired: 0 };
  }
}

// ==================================================
// ===== Cron Job (Every Day at 11:20 AM) =====
// ==================================================
cron.schedule("10 14 * * *", async () => {
  console.log("⏰ Running daily auto reminder job at 11:20 AM...");
  await sendRemindersCore();
});

// ==================================================
// ===== API Controllers =====
// ==================================================

// GET /api/renewals
exports.list = async (req, res) => {
  try {
    const {
      q = '',
      sortBy = 'renewalDate',
      order = 'asc',
      page = 1,
      limit = 20,
    } = req.query;

    const numericPage = Math.max(parseInt(page, 10) || 1, 1);
    const numericLimit = Math.min(Math.max(parseInt(limit, 10) || 20, 1), 200);

    const query = q
      ? {
          $or: [
            { name: { $regex: q, $options: 'i' } },
            { type: { $regex: q, $options: 'i' } },
            { description: { $regex: q, $options: 'i' } },
            { project: { $regex: q, $options: 'i' } },
            { contactEmail: { $regex: q, $options: 'i' } },
          ],
        }
      : {};

    const sort = { [sortBy]: order === 'desc' ? -1 : 1 };

    const [data, total] = await Promise.all([
      Renewal.find(query).sort(sort)
        .skip((numericPage - 1) * numericLimit)
        .limit(numericLimit)
        .lean(),
      Renewal.countDocuments(query),
    ]);

    // Add properly parsed dates for display
    const dataWithParsedDates = data.map(item => ({
      ...item,
      parsedRenewalDate: parseDate(item.renewalDate),
      displayDate: formatDateForDisplay(parseDate(item.renewalDate))
    }));

    res.json({
      data: dataWithParsedDates,
      page: numericPage,
      limit: numericLimit,
      total,
      pages: Math.ceil(total / numericLimit),
    });
  } catch (err) {
    console.error('renewals.list error:', err);
    res.status(500).json({ message: 'Failed to fetch renewals' });
  }
};

// GET /api/renewals/alerts?days=15
exports.alerts = async (req, res) => {
  try {
    const days = Math.max(parseInt(req.query.days, 10) || 15, 1);
    const today = new Date(); today.setHours(0, 0, 0, 0);
    const soon = new Date(today); soon.setDate(soon.getDate() + days);

    const allRenewals = await Renewal.find().lean();
    
    const expired = allRenewals.filter(record => {
      const recordDate = parseDate(record.renewalDate);
      return recordDate < today;
    }).sort((a, b) => parseDate(a.renewalDate) - parseDate(b.renewalDate));

    const dueSoon = allRenewals.filter(record => {
      const recordDate = parseDate(record.renewalDate);
      return recordDate >= today && recordDate <= soon;
    }).sort((a, b) => parseDate(a.renewalDate) - parseDate(b.renewalDate));

    res.json({ 
      expired: expired.map(item => ({
        ...item,
        parsedRenewalDate: parseDate(item.renewalDate),
        displayDate: formatDateForDisplay(parseDate(item.renewalDate))
      })),
      dueSoon: dueSoon.map(item => ({
        ...item,
        parsedRenewalDate: parseDate(item.renewalDate),
        displayDate: formatDateForDisplay(parseDate(item.renewalDate))
      })),
      days 
    });
  } catch (err) {
    console.error('renewals.alerts error:', err);
    res.status(500).json({ message: 'Failed to fetch alerts' });
  }
};

// GET /api/renewals/:id
exports.getOne = async (req, res) => {
  try {
    const doc = await Renewal.findById(req.params.id).lean();
    if (!doc) return res.status(404).json({ message: 'Not found' });
    
    // Add parsed date for display
    const docWithParsedDate = {
      ...doc,
      parsedRenewalDate: parseDate(doc.renewalDate),
      displayDate: formatDateForDisplay(parseDate(doc.renewalDate))
    };
    
    res.json(docWithParsedDate);
  } catch (err) {
    console.error('renewals.getOne error:', err);
    res.status(500).json({ message: 'Failed to fetch renewal' });
  }
};

// POST /api/renewals
exports.create = async (req, res) => {
  try {
    const payload = {
      name: req.body.name,
      type: req.body.type,
      description: req.body.description,
      project: req.body.project,
      contactEmail: req.body.contactEmail,
      renewalDate: req.body.renewalDate,
    };
    const created = await Renewal.create(payload);
    res.status(201).json(created);
  } catch (err) {
    console.error('renewals.create error:', err);
    res.status(400).json({ message: err.message || 'Failed to create' });
  }
};

// PUT /api/renewals/:id
exports.update = async (req, res) => {
  try {
    const payload = {
      name: req.body.name,
      type: req.body.type,
      description: req.body.description,
      project: req.body.project,
      contactEmail: req.body.contactEmail,
      renewalDate: req.body.renewalDate,
    };
    const updated = await Renewal.findByIdAndUpdate(
      req.params.id,
      payload,
      { new: true, runValidators: true }
    );
    if (!updated) return res.status(404).json({ message: 'Not found' });
    res.json(updated);
  } catch (err) {
    console.error('renewals.update error:', err);
    res.status(400).json({ message: err.message || 'Failed to update' });
  }
};

// DELETE /api/renewals/:id
exports.remove = async (req, res) => {
  try {
    const deleted = await Renewal.findByIdAndDelete(req.params.id);
    if (!deleted) return res.status(404).json({ message: 'Not found' });
    res.json({ ok: true });
  } catch (err) {
    console.error('renewals.remove error:', err);
    res.status(500).json({ message: 'Failed to delete' });
  }
};

// GET /api/renewals/send-reminders (manual trigger for testing)
exports.sendReminders = async (req, res) => {
  try {
    const result = await sendRemindersCore();
    res.json({ 
      message: "Reminder job executed manually", 
      upcomingSent: result.upcoming,
      expiredSent: result.expired
    });
  } catch (err) {
    console.error("sendReminders error:", err);
    res.status(500).json({ message: "Failed to send reminders" });
  }
};

// GET /api/renewals/debug-dates (new endpoint to check date parsing)
exports.debugDates = async (req, res) => {
  try {
    const allRenewals = await Renewal.find().lean();
    
    const debugData = allRenewals.map(record => {
      const parsedDate = parseDate(record.renewalDate);
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      
      return {
        name: record.name,
        originalDate: record.renewalDate,
        parsedDate: parsedDate.toISOString(),
        displayDate: formatDateForDisplay(parsedDate),
        status: parsedDate < today ? 'EXPIRED' : parsedDate <= new Date(today.getTime() + 15 * 24 * 60 * 60 * 1000) ? 'UPCOMING' : 'FUTURE',
        daysDifference: Math.ceil((parsedDate - today) / (1000 * 60 * 60 * 24))
      };
    });

    res.json(debugData);
  } catch (err) {
    console.error('renewals.debugDates error:', err);
    res.status(500).json({ message: 'Failed to debug dates' });
  }
};